// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FileUploader() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"file_upload\" data-on-load=\"$$get\" data-store=\"\"><script>\r\n    function startTask() {\r\n      // Establish WebSocket connection\r\n      const socket = new WebSocket('ws://localhost:8080/ws');\r\n      \r\n      socket.onmessage = function (event) {\r\n      \t\t       console.log('Message from server ', event.data);\r\n      };\r\n\r\n      //fetch('/start')\r\n      //  .then(response => response.json())\r\n      //  .then(data => {\r\n      //    console.log(data.message); // Start WebSocket\r\n      //  });\r\n    }\r\n  </script><div><div class=\"flex flex-col items-center justify-center my-8\"><label for=\"file-upload\" class=\"cursor-pointer bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\">Buscar archivos</label> <input id=\"file-upload\" type=\"file\" data-model=\"files\" multiple class=\"hidden\"></div><div class=\"flex justify-center container mx-auto\"><button class=\"mx-auto border-solid border-2 border-indigo-600 mt-4\" onclick=\"startTask()\">Enviar</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
